### ISSUE TITLE
Incorrect bounds on http-client-tls

### ISSUE THREAD

**Issue by tfausak** [snoyberg/http-client#482]
I think the bounds that http-client-tls has for http-client are wrong. http-client version 0.7.11 added the [`strippedHostName `](https://hackage.haskell.org/package/http-client-0.7.11/docs/Network-HTTP-Client.html#v:strippedHostName) function. http-client-tls version uses that (for example [here](https://github.com/snoyberg/http-client/blob/c61ea7d63ac2e95034f539cd0bbf1c677e837f1e/http-client-tls/Network/HTTP/Client/TLS.hs#L124)) but claims to work with any [http-client >= 0.5](https://github.com/snoyberg/http-client/blob/c61ea7d63ac2e95034f539cd0bbf1c677e837f1e/http-client-tls/http-client-tls.cabal#L21). This causes build errors like this:

```
[1 of 1] Compiling Network.HTTP.Client.TLS ( Network/HTTP/Client/TLS.hs, dist/build/Network/HTTP/Client/TLS.o, dist/build/Network/HTTP/Client/TLS.dyn_o )

Network/HTTP/Client/TLS.hs:124:39: error:
    Variable not in scope:
      strippedHostName
        :: String -> connection-0.3.1:Network.Connection.Types.HostName
    |
124 |             { NC.connectionHostname = strippedHostName host
    |                                       ^^^^^^^^^^^^^^^^

Network/HTTP/Client/TLS.hs:141:39: error:
    Variable not in scope:
      strippedHostName
        :: String -> connection-0.3.1:Network.Connection.Types.HostName
    |
141 |             { NC.connectionHostname = strippedHostName serverName
    |                                       ^^^^^^^^^^^^^^^^

Network/HTTP/Client/TLS.hs:147:54: error:
    Variable not in scope:
      strippedHostName
        :: String -> connection-0.3.1:Network.Connection.Types.HostName
    |
147 |                     Nothing -> Just $ NC.OtherProxy (strippedHostName host) $ fromIntegral port
    |                                                      ^^^^^^^^^^^^^^^^
```

Fortunately a workaround is simple: use http-client-tls < 0.3.6.

**Comment by snoyberg** [comment]
CC @robx

**Comment by robx** [comment]
Yeah, `http-client-tls` version 0.3.6 should have a lower bound on `http-client` of 0.7.11.

**Comment by snoyberg** [comment]
I’ll accept a PR to fix this, but I’m not going to spend time on Hackage revisions. If someone else wants to I’ll grant maintainer rights.

**Comment by ysangkok** [comment]
@snoyberg Thank you a lot for the merge. I can do a revision if you'd grant maintainer rights to [my user](https://hackage.haskell.org/user/janus). If you'd rather not, would it be possible to make the release of 0.3.6.1? Then this package would be buildable in the next nightly. It's not buildable in the current nightly.

**Comment by snoyberg** [comment]
I've uploaded the new http-client-tls and given you maintainer access on Hackage to the four packages in this repo.

**Comment by juhp** [comment]
I [ran](https://github.com/juhp/fbrnch/runs/5174432497?check_suite_focus=true) into this today,
so it would still be good to revise http-client-tls-0.3.6, @ysangkok

**Comment by ysangkok** [comment]
Thank you snoyberg for the maintainer bit and for the release. Juhp, I have made a new revision for [http-client-openssl 0.3.3](https://hackage.haskell.org/package/http-client-openssl-0.3.3/revisions/) and for [http-client-tls 0.3.6](https://hackage.haskell.org/package/http-client-tls-0.3.6/revisions/). Hopefully it will fix your issue, let me know if there are any more problems. Cheers!
