### PR TITLE
http-conduit: depend on attoparsec-aeson to allow aeson-2.2

### LINKED ISSUE #511: http-conduit fails to build with GHC 9.4 and aeson 2.2.0.0
```
[3 of 3] Compiling Network.HTTP.Simple ( Network/HTTP/Simple.hs, /tmp/http-conduit-2.3.8.2/dist-newstyle/build/x86_64-linux/ghc-9.4.5/http-conduit-2.3.8.2/build/Network/HTTP/Simple.o, /tmp/http-conduit-2.3.8.2/dist-newstyle/build/x86_64-linux/ghc-9.4.5/http-conduit-2.3.8.2/build/Network/HTTP/Simple.dyn_o )

Network/HTTP/Simple.hs:106:1: error:
    Could not load module ‘Data.Aeson.Parser’
    It is a member of the hidden package ‘aeson-2.1.2.1’.
    Perhaps you need to add ‘aeson’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
    |
106 | import Data.Aeson.Parser (json')
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The package bounds need to be revised to only allow `aeson <2.2`

### PR DESCRIPTION
**Pull request by juhp**
replaces #510
closes #511

### CODE REVIEW

**Review by snoyberg — APPROVED** [review]

**Comment by snoyberg** [comment]
Thanks!
