### ISSUE TITLE
http-conduit does not build with aeson-2.2.0.0+

### ISSUE THREAD

**Issue by simonmichael** [snoyberg/http-client#580]
When the `aeson` flag is true, as it is by default, http-conduit fails to build with aeson 2.2.0.0 or newer:

```
http-conduit      > [3 of 3] Compiling Network.HTTP.Simple                                                                                                                                           
http-conduit      >                                                                                                                                                                                  
http-conduit      > /private/var/folders/r7/f9j9c2zd1k97v47cr84j_qvc0000gp/T/stack-529e7a7a15c2c8d1/http-conduit-2.3.9.1/Network/HTTP/Simple.hs:106:1: error:                                        
http-conduit      >     Could not find module ‘Data.Aeson.Parser’                                                                                                                                    
http-conduit      > ...
http-conduit      >     |                                                                                                                                                                            
http-conduit      > 106 | import Data.Aeson.Parser (json')                                                                                                                                           
http-conduit      >     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                           
```

Probably needed:
- revisions for the current and past hackage releases, setting a aeson < 2.2 upper bound
- code updates to support aeson 2.2.0.0 and aeson 2.3.0.0.

**Comment by sol** [comment]
CI is currently failing for GHC 9.14 due to some dependencies still imposing overly restrictive upper bounds, preventing them from being built with GHC 9.14.

CI is only useful if we keep it green. For that reason I will temporarily disable those jobs.

However, @simonmichael I still don't see the `aeson` issue on CI.

**Comment by simonmichael** [comment]
I think this was a false alarm. I see that module is provided by attoparsec-aeson now. I think maybe my failing builds all were using older attoparsec-aeson-2.1.0.0, which is a dummy package containing nothing. So there may be a bounds issue still to be fixed somewhere, but it's beyond me right now. I'll close this.
