### PR TITLE
http-client-tls, http-client-openssl: Fix lower bounds on http-client

### LINKED ISSUE #482: Incorrect bounds on http-client-tls
I think the bounds that http-client-tls has for http-client are wrong. http-client version 0.7.11 added the [`strippedHostName `](https://hackage.haskell.org/package/http-client-0.7.11/docs/Network-HTTP-Client.html#v:strippedHostName) function. http-client-tls version uses that (for example [here](https://github.com/snoyberg/http-client/blob/c61ea7d63ac2e95034f539cd0bbf1c677e837f1e/http-client-tls/Network/HTTP/Client/TLS.hs#L124)) but claims to work with any [http-client >= 0.5](https://github.com/snoyberg/http-client/blob/c61ea7d63ac2e95034f539cd0bbf1c677e837f1e/http-client-tls/http-client-tls.cabal#L21). This causes build errors like this:

```
[1 of 1] Compiling Network.HTTP.Client.TLS ( Network/HTTP/Client/TLS.hs, dist/build/Network/HTTP/Client/TLS.o, dist/build/Network/HTTP/Client/TLS.dyn_o )

Network/HTTP/Client/TLS.hs:124:39: error:
    Variable not in scope:
      strippedHostName
        :: String -> connection-0.3.1:Network.Connection.Types.HostName
    |
124 |             { NC.connectionHostname = strippedHostName host
    |                                       ^^^^^^^^^^^^^^^^

Network/HTTP/Client/TLS.hs:141:39: error:
    Variable not in scope:
      strippedHostName
        :: String -> connection-0.3.1:Network.Connection.Types.HostName
    |
141 |             { NC.connectionHostname = strippedHostName serverName
    |                                       ^^^^^^^^^^^^^^^^

Network/HTTP/Client/TLS.hs:147:54: error:
    Variable not in scope:
      strippedHostName
        :: String -> connection-0.3.1:Network.Connection.Types.HostName
    |
147 |                     Nothing -> Just $ NC.OtherProxy (strippedHostName host) $ fromIntegral port
    |                                                      ^^^^^^^^^^^^^^^^
```

Fortunately a workaround is simple: use http-client-tls < 0.3.6.

### PR DESCRIPTION
**Pull request by robx**
Fixes #482.

### CODE REVIEW

**Comment by robx** [comment]
I don't understand how this change breaks CI:

```
2022-02-08T08:41:33.4835361Z http-client          > Building library for http-client-0.7.11..
2022-02-08T08:41:33.6792265Z http-client          > [ 1 of 19] Compiling Data.KeyedPool
2022-02-08T08:41:34.4020164Z http-client          > [ 2 of 19] Compiling Network.HTTP.Client.Types
2022-02-08T08:41:38.3210581Z http-client          > [ 3 of 19] Compiling Network.HTTP.Client.Connection
2022-02-08T08:41:38.3433680Z http-client          > 
2022-02-08T08:41:38.3447457Z http-client          > /home/vsts/work/1/s/http-client/Network/HTTP/Client/Connection.hs:232:76: error:
2022-02-08T08:41:38.3452921Z http-client          >     • Variable not in scope: (<>) :: t0 -> String -> IO Bool
2022-02-08T08:41:38.3457184Z http-client          >     • Perhaps you meant one of these:
2022-02-08T08:41:38.3461176Z http-client          >         ‘<$>’ (imported from Prelude), ‘<*>’ (imported from Prelude),
2022-02-08T08:41:38.3464883Z http-client          >         ‘>>’ (imported from Control.Monad)
2022-02-08T08:41:38.3467972Z http-client          >     |
2022-02-08T08:41:38.3471257Z http-client          > 232 |             _               -> error $ "tryAddresses invariant violated: " <> show addresses
2022-02-08T08:41:38.3474445Z http-client          >     |                                                                            ^^
```

**Comment by robx** [comment]
Oh, it's broken on master.

**Review by snoyberg — APPROVED** [review]
