### ISSUE TITLE
fails to build with Win32-2.6

### ISSUE THREAD

**Issue by joeyh** [snoyberg/http-client#309]
C:\Users\jenkins\AppData\Local\Temp\stack4956\http-client-0.5.7.0\Network\HTTP\Proxy.hs:177:43: error:
        * Couldn't match type `Maybe [Char]' with `[Char]'
          Expected type: String
            Actual type: Maybe [Char]
        * In the second argument of `regQueryValue', namely
            `(Just "ProxyServer")'
          In a stmt of a 'do' block:
            server <- regQueryValue hkey (Just "ProxyServer")
          In the expression:
            do { server <- regQueryValue hkey (Just "ProxyServer");
                 exceptions <- try $ regQueryValue hkey (Just "ProxyOverride") ::
                                 IO (Either IOException String);
                 return $ Just (server, either (const "") id exceptions) }

**Comment by snoyberg** [comment]
I don't have easy access to a Windows machine to test on. Would you be able to confirm that 9207033 fixes the issue before I make a release?

**Comment by joeyh** [comment]
Failed on line 178, which seems to need the same change.

- exceptions <- try $ regQueryValue hkey (Just "ProxyOverride") 
+ exceptions <- try $ regQueryValue hkey "ProxyOverride"

I have not checked past this point.

(Also, https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ might be useful for you.)

**Comment by snoyberg** [comment]
Thanks for #310, closing.
